name: Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          config_timezone: Asia/Calcutta
          token: ${{ secrets.METRICS_TOKEN }}
          filename: profile.svg

          # Isometric Plugin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Starred Topics Plugin
          plugin_topics: yes
          plugin_topics_mode: icons

          # Leetcode Plugin
          plugin_leetcode: yes
          plugin_leetcode_user: vineethchivukula

          # Anilist Plugin
          plugin_anilist: yes
          plugin_anilist_user: vinny267
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, reading
          plugin_anilist_limit: 3
          plugin_anilist_shuffle: yes
